#!/usr/bin/env python3
# plot 2D histograms of molecular properties (present in *.nc files)

import pylab as plt
import xarray as xr
import numpy as np
from pathlib import Path

from matplotlib.markers import MarkerStyle as MS
markers = { 1: ('Rossetti Nonbinders', MS('o', 'full').scaled(0.1)),
            2: ('Rossetti Binders', MS('o', 'full').scaled(0.5)),
            3: ('Rossetti Nonspecific', MS('+', 'none').scaled(0.5)),
            #0: ('Smith Hits', MS('*', 'full').scaled(0.5)),
          }

# autodock cutoff, copied from src/dataset/sublists.py
cut = { 'MPro_5R84' : -13.220
      , 'MPro_6WQF' : -12.865
      , 'PLPro_7JIR': -15.261
      , 'NSP15_6WLC': -13.534
      , 'Spike_6M0J': -11.739
      , 'RDRP'      : -12.435
      }

def read_counts(name):
    return xr.open_dataset(name)['count']

# Note: we "guess" which direction the xy box goes because
# negative scores want to be as neg as possible and pos. want
# to be as pos. as possible.
def guess_sl(z):
    if z < 0:
        return slice(None,z)
    else:
        return slice(z,None)

def plot(H, x0, y0, loc=None, points=None):
    dim0, dim1 = H.dims
    fig, ax = plt.subplots(figsize=(4.5,3.5))
    #np.log(H+0.5).plot(ax=ax)
    xr.plot.imshow(np.log(H+0.5), ax=ax, zorder=-1)

    if x0 is not None:
        plt.axhline(x0, color='black', linewidth=1, zorder=1)
    if y0 is not None:
        plt.axvline(y0, color='black', linewidth=1, zorder=1)

    if points is not None:
        # Doesn't show up using x,y order -- xr swaps axes!!!
        for c, (name,style) in markers.items():
            u = points.loc[points['color'] == c]
            ax.scatter(u[dim1], u[dim0],
                       marker=style, label=name, zorder=10)
        ax.legend(loc='upper right', fontsize='x-small')

    plt.tight_layout()
    if loc:
        plt.savefig(loc / f'{dim0}-{dim1}.pdf')

def main(argv):
    points = None
    if len(argv) >= 4 and argv[1] == "--points":
        # Read a plot-points file, consisting of score
        # values and colors (e.g. as generated by rossetti.py)
        import pandas as pd
        points = pd.read_csv(argv[2])
        del argv[1:3]
    assert len(argv) == 2, f"Usage: {sys.argv[0]} <dir>"
    loc = Path(argv[1])
    assert loc.is_dir()

    cutoff = cut[loc.parent.name]

    H = read_counts(loc / "atoms_score.nc")
    plot(H, None, cutoff, loc, points)
    plt.clf()

    H = read_counts(loc / "atoms_tors.nc").sel(tors=slice(None, 20))
    plot(H, None, None, loc, points)
    plt.clf()

    H = read_counts(loc / "tors_score.nc").sel(tors=slice(None, 20))
    plot(H, None, cutoff, loc, points)
    plt.clf()

    return 0

if __name__=="__main__":
    import sys
    exit( main(sys.argv) )
